### ISSUE TITLE
Refactor the Turn methods to be more functional for the Player class

### ISSUE THREAD

**Issue by Abarucija** [mttmortensen/ygo_#3]

**Comment by mttmortensen** [comment]
Turn methods will need to be a Turn class. We can bring in the turn methods from the Player class but replace it with a play_turn method to call on the Turn class. Or we initialize it through the Game class and push it through the to the Player class

**Comment by mttmortensen** [comment]
This is now done. Turn and BattlePhase class have been created and introduced into the game. All bugs fixed from it.
